service: sls-auth
frameworkVersion: '3'

useDotenv: true
 

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  login:
    handler: src/functions/login.handler
    events:
      - httpApi:
          path: /login
          method: post
  register:
    handler: src/functions/register.handler
    events:
      - httpApi:
          path: /register
          method: post


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
